### ISSUE TITLE
Nemoh test case .h5 file not generated/Individual test case errors.

### ISSUE THREAD

**Issue by ahagmuller** [WEC-Sim/bemio#16]
Hi,
After running test_install.py, the NEMOH cases do not appear to actually generate .h5 files even though it appears to have run successfully as per below (statement shows all test cases ran successfully and .h5 files are generated for WAMIT test cases):

Writing HDF5 data to /home/user/bemio/tutorials/nemoh/data/two_body/Nemoh.h5
	Radiation state space coefficients for Cube.dat were not written.
	Radiation state space coefficients for Rotated_cube.dat were not written.
****The tutorials/nemoh test case ran successfully****

When I run just the NEMOH case i get a similar error from running in windows:

Traceback (most recent call last):
** IDLE Internal Exception: 
  File "/usr/lib/python2.7/idlelib/run.py", line 324, in runcode
    exec code in self.locals
  File "/home/user/bemio/tutorials/nemoh/run.py", line 3, in <module>
    from bemio.io.nemoh import read
ImportError: cannot import name read

and when I run just the WAMIT RM3 test case i get the following error:

Traceback (most recent call last):
** IDLE Internal Exception: 
  File "/usr/lib/python2.7/idlelib/run.py", line 324, in runcode
    exec code in self.locals
  File "/home/user/bemio/tutorials/wamit/rm3/run.py", line 2, in <module>
    from bemio.io.wamit import read
ImportError: cannot import name read

Thanks!

Alex

**Comment by lawsonro3** [comment]
Hi Alex,

A couple of things:

1. I just tested the latest version of bemio with a clean install of Anaconda in Windows and everything ran correctly. Please try downloading the latest version of bemio and typing the following commands from the Windows command prompt:

  ```
  cd <Location of your bemio source folder>
  python setup.py install --user
  python install_test.py
  ```

  I get the following success message:

  ```
  Test cases runs completed:
        tutorials/wamit/COER_hydrodynamic_modeling_comp: SUCCESS
        tutorials/wamit/wec3: SUCCESS
        tutorials/nemoh: SUCCESS
        tutorials/aqwa: SUCCESS
  ```

2. Regarding the "space coefficients not written" message. They indeed should not be written because they were not calculated in the Nemoh tutorial case. Other data is written to the hydro data file.

3. I'm guessing that the error "ImportError: cannot import name read" is due to the fact that you did not execute

  ```
  python setup.py install --user
  ```

  from the base bemio directory or because you did not update t o the latest version of bemio.

Let me know if you are still having problems after trying the suggestions in this post.

-Mike

**Comment by ahagmuller** [comment]
HI Mike,
I did the clean install and ran the commands and everything appeared to
have worked, the nemoh.h5 file is now generated. However, when I ran the
individual test case for nemoh, it did run and generate a file, but it did
have the following error at the beginning:


Warning (from warnings module):
  File "C:\Users\Master\Anaconda\lib\site-packages\PIL\Image.py", line 81
    warnings.warn(str(v), RuntimeWarning)
RuntimeWarning: The _imaging extension was built for another  version of
Pillow or PIL
Normalizing hydro coefficients by rho, g, and w...
Spring stiffness not nondimensionalized
Normalizing hydro coefficients by rho, g, and w...
Spring stiffness not nondimensionalized


Also,
When running NEMOH as opposed to WAMIT, do we need to have a very small
value for the initial wave frequency to be run, say .001 or so, since there
is no zero added mass calculated directly? I read this in a forum as a
temporary solution until NEMOH is updated to do this directly.
Thanks!

Alex

**Comment by lawsonro3** [comment]
Not sure about the error:

```
RuntimeWarning: The _imaging extension was built for another  version of
Pillow or PIL
```

but if the files are writing and everything works I would not worry about it.

Regarding the inf frequency added mass - I just fixed the code so that it reads the inf freq added mass out of the IRF.tec file generated by Nemoh. Just update to the latest version.

Let us know if you have any issues with this.
