### ISSUE TITLE
Aqwa zero and inf. frequency added mass scaling

### ISSUE THREAD

**Issue by mmacn** [WEC-Sim/bemio#37]
We've found an issue relating to the added mass from an Aqwa file. The zero- and infinite-frequency added mass are apparently scaled twice by the density, which gives values that are too small.

It looks like the issue is in bem.HydrodynamicData.scale-- am.inf and am.zero are both bound to elements in am.all, so they are scaled by density when am.all is, and then a second time when am.inf and am.zero are scaled.

**Comment by cmichelen** [comment]
The issue is that unlike WAMIT and NEMOH, AQWA does not output infinite frequency added mass. Instead we use the largest frequency. For WAMIT and NEMOH these two need to be scaled separately, but for NEMOH that implementation results in double scaling. 

The zero frequency added mass is probably being double scaled for all 3 BEM codes. 

We will look into resolving this.

**Comment by cmichelen** [comment]
Should be fixed now. 

In Python `b = a` does not create a copy of `a` but rather creates a new reference to the same data. both `a`and `b` where normalized, causing the same data to be normalized twice. Using `b = np.copy(a)` solves the problem.

**Comment by yuyihsiang** [comment]
Thanks,

- Yi-Hsiang

**Comment by ahagmuller** [comment]
Hi ,
Does this mean it is fixed for NEMOH as well?
Thanks again,
Alex

**Comment by cmichelen** [comment]
I don't think it was a problem in NEMOH actually.

**Comment by mmacn** [comment]
Thanks very much for taking a look at this.
